### ISSUE TITLE
backprojection

### ISSUE THREAD

**Issue by yscoffee** [YinghaoHuang91/InterCap#1]
Thank you for open sourcing this dataset!

Could you explain the calibaration files for peforming depth back-projection (depth to world space) ?
I found 3 different calibartion directories at: https://github.com/YinghaoHuang91/InterCap/tree/master/Data
wondering that which one is mapped to the recording 01/01/Seg_0/Frames_Cam1

**Comment by YinghaoHuang91** [comment]
Hi, thanks to your interest in our work. You may find the correspondence in this file: https://github.com/YinghaoHuang91/InterCap/blob/master/obj_track/utils.py, from line 56 to line 63.

**Comment by yscoffee** [comment]
thanks!
